name: DL_project_2023
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - torchmetrics
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl
  - pip:
    - torchviz
    - einops
    - torchmetrics
